replicaCount: 2


image:
  repository: khanhle04/orchestrator-agent
  tag: v1.0.1
  pullPolicy: IfNotPresent


podAnnotations: {}


resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi
  


affinity: {}
nodeSelector: {}
tolerations: []


service:
  type: ClusterIP
  port: 7010 # Service port (client-facing)
  targetPort: 7010 # Container port app lắng nghe (chỉnh nếu app khác)


ingress:
  enabled: true
  className: nginx
  annotations: {}
# ví dụ bật rewrite: nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: orchestrator.khanklee.id.vn
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: false
    secretName: orchestrator-agent-tls # dùng khi enabled=true


container:
  name: orchestrator-agent
  port: 7010 # trùng với service.targetPort ở trên
  command: [] # ví dụ: ["/bin/app", "--flag"]
  args: [] # ví dụ: ["--config=/etc/app/config.yaml"]
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  


sealedSecrets:
  enabled: true

  name: orchestrator-agent-sealed-secret
  namespace: orchestrator-agent

  encryptedData:
    GOOGLE_API_KEY: "AgBQTDIWsr6076H3EHg2Yh0pom226sJFxM7L+mZkUEuy9VUUlf8rQUDTk6WoFFQG5VKHQ52nSpDYfB/uGFfYIkFyM9e+5RXblVlEplxophjh5CrJE/UBi+HlO1jZrR9cTo7Y5PyVdkmPiWni9LL9Dju8kq4SWQV+IYssAuKcJZGFgNtB/0Ri0OGIfS/wD1joUnfx9jY8HckFcKy+8MYkZnDD3ENK1Yk0Cj2ief04EovrdvUJYCdXm0Q/uwFwesasG+Qpin4GXmXip0ejYftqW4R/BgazQtU6V00+7/bdgst79I88NIcVOtwECaCrkQbME7Bozmq7lPPYnxZ3F0IRVIdnNaaZNtjHvDCHUnd7Rg2qIxZ7gZDXbdLsArjHVHg2jojqpkc8ftxDzVCrFIr7j/mKC+Ak3WvL2xphPhgdGZspmUmU1FOS3cRZavZMYb+Wa7Gjrx9o+60W/kjFK1p6E0Yvf373Bn8V6B0DD5LBGdFuDornE7dmxhfQGjc0WmO7MZSHzDnlqYuIHGn8VnnEzZ7bIEeCkj168zLDJuUj/ZMavhSN23DgdmYfkE+eXGMFTFngz7JEvzJl9zYfoJWZfCplPDSav2SPY0tILMDCmlBs8Fw8/3KKts34URZcEdCrucgbaNYKa+6PPzTaa5uJK0pASOvUIRDO5gx4EQiF6lQgJo49c9D85VuX+r9BAQEH8s785u6gHyJ/IAPz7SSS3RavErSxnV/snqe0gRICtMa0Ybhks4ix+Uw="
    REDIS_PASSWORD: "AgAKnCBIIQf+qIjgWVpaFrCYepRgtThd0OL/SXpCzuhQzTAiQhA7TzKRd3uTESBezV31aVN6Kf8GNBuopWQgaU7QmeqK+3FSsLgOe27H4AiLdiUYUQmAmCg0PfRAan7cSQEIbXh0ZWSbaeUkmTvPKEp3Jh7ZUR2e41qBb8dS1fCPrTLILBP8Ex40S5ThzqFcIPQIsmjIzOFsVuQzIGJ0ZQfQWiJaziJxgk3ovxaOTOeyzaJ1gD+SISnia55H9e6ETmxIJ9kcVHyQot1AyJKanLZKIjZtGIrwtd+2K7QSZZM14kzD1EbY5U+OYNug8X71ETBwUWV8GDGng0urequtTIO5K9Fc2xtiY1/gY/IsxCISQk89ayCGDllzbglrXNctucfOpJg3EtuZEt4ugmKLjxlxsjbT7FdR8OFEbO4nuvq8+RDyPcjqLD0DvCMj5r277mvI66fl5jYUo2g/fBcvQ79kInHwu0pKR6GprvcoxrV2wXCXGwul0JVrYMWteTtMjKlLBYiYwEj/jXGWoMu6lFJ/qibNOAY4nwBqgFPWWtPHr0CayuAacpb5Ku9hxIsZVqedFmK+34Nv8at9mripu9Zzn6iZjy8Xhf+SxxENuOnC6W5b1dclBEdCQXRnLUDlT+zYVJHmLr1Y6F+ZLjP3lg5JgDWcEeifC+3Q9oVYCXsWh9qG0qbj3BW8LJVDaMdGKt1c5/79QHaMHriL"

existingSecret:
  enabled: true
  name: "orchestrator-agent-sealed-secret" # Tên secret đã có sẵn trong cluster để inject biến môi trường

config:
  enabled: true
  data:
    REDIS_HOST: "redis-master.redis.svc.cluster.local"
    REDIS_PORT: 6379
    REDIS_DB: "0"
    RAG_AGENT_URL: "rag-agent.rag-agent.svc.cluster.local"
    ORCHESTRATOR_AGENT_PORT: 7010
    ORCHESTRATOR_AGENT_HOST: "0.0.0.0"

